---
title: "R Studio - Shiny"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: flatly
---

$~$

# Shiny app

Here is the basic set up for a Shiny app.

```{r}
library(shiny)

ui <- fluidPage()

server <- function(input, output) {}

shinyApp(ui = ui, server = server)
```

$~$

Let's create a basic map using Shiny. 

```{r}
library(shiny)
library(leaflet)

ui <- fluidPage(leafletOutput("map"))

server <- function(input, output, session) {
  
  output$map <- renderLeaflet({
    library(leaflet)
    leaflet() %>%
      addTiles()})}

shinyApp(ui, server)
```

```{r echo = FALSE}
knitr::include_app("https://marinespatialviz.shinyapps.io/Map1/", height = "600px")
```
  
$~$

# View and basemap

Let's change the basemap and the view.

```{r}
library(shiny)
library(leaflet)

ui <- fluidPage(leafletOutput("mymap"))

server <- function(input, output, session) {
  
  output$mymap <- renderLeaflet({
    library(leaflet)
    leaflet() %>%
      setView(lng = -15, lat = 20, zoom = 1) %>%
      addTiles() %>%
      addProviderTiles(providers$Esri.WorldImagery)})}

shinyApp(ui, server)
```

```{r echo = FALSE}
knitr::include_app("https://marinespatialviz.shinyapps.io/Map2/")
```

$~$

# Marker

Using the example from the R Studio [section](https://marinespatialviz.github.io/marinespatialviz/rstudio.html#marker), let's add a marker. 

```{r}
library(shiny)
library(leaflet)

ui <- fluidPage(leafletOutput("mymap"))

server <- function(input, output, session) {
  
  output$mymap <- renderLeaflet({
    library(leaflet)
    leaflet() %>%
      addTiles() %>%
      setView(lng = 142, lat = 11, zoom = 3) %>%
      addMarkers(lng = 142.1999992, lat = 11.3499986) %>%
      addProviderTiles(providers$Esri.OceanBasemap)})}

shinyApp(ui, server)
```

```{r echo = FALSE}
knitr::include_app("https://marinespatialviz.shinyapps.io/marker/")
```

$~$

## Pop-up marker

$~$

## Cluster marker

$~$

# Polyline

Let's add the Equator to the map. 

```{r}
library(shiny)
library(leaflet)

x = c(-180, 180)
y = c(0, 0)
e = data.frame(x, y)

ui <- fluidPage(leafletOutput("mymap"))

server <- function(input, output, session) {
  
  output$mymap <- renderLeaflet({
    library(leaflet)
    leaflet() %>%
      addTiles() %>%
      setView(lng = 0, lat = 0, zoom = 2) %>%
      addPolylines(lng = e$x, lat = e$y, color = "red") %>%
      addProviderTiles(providers$Esri.OceanBasemap)})}

shinyApp(ui, server)
```

```{r echo = FALSE}
knitr::include_app("https://marinespatialviz.shinyapps.io/polyline/")
```

#Polygon

Let's also highlight the tropics. 

```{r}
library(shiny)
library(leaflet)

x = c(-180, 180, 180, -180)
y = c(23.5, 23.5, -23.5, -23.5)
e = data.frame(x, y)

ui <- fluidPage(leafletOutput("mymap"))

server <- function(input, output, session) {
  
  output$mymap <- renderLeaflet({
    library(leaflet)
      leaflet() %>%
      addTiles() %>%
      setView(lng = 0, lat = 0, zoom = 2) %>%
      addPolygons(lng = e$x, lat = e$y, color = "orange", fillOpacity = .5) %>% 
      addProviderTiles(providers$Hydda.Base)})}

shinyApp(ui, server)
```

```{r echo = FALSE}
knitr::include_app("https://marinespatialviz.shinyapps.io/polygon/")
```
